#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
# set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

download_default_settings ()
{
	if [[ ! -f "${SITEDIR_PATH}/default.settings.local.php" ]]; then
		#if the default.settings.local.php file doesn't exist, go out and download it.
		if [[ -d "${DOCROOT_PATH}/config" ]]; then
			# Drupal 8
			wget --no-check-certificate -O "${SITEDIR_PATH}/default.settings.local.php" https://raw.githubusercontent.com/docksal/drupal8/master/docroot/sites/default/default.settings.local.php
		else
			# Drupal 7
			wget --no-check-certificate -O "${SITEDIR_PATH}/default.settings.local.php" https://raw.githubusercontent.com/docksal/drupal7/master/docroot/sites/default/example.settings.local.php
		fi
	fi
}

# Initialize local settings files
init_settings ()
{
	rm -f "${SITEDIR_PATH}/settings.local.php"
	# Copy from settings templates
	copy_settings_file "${SITEDIR_PATH}/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
	chmod 755 "${SITEDIR_PATH}/settings.php"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install -y --site-name='My Drupal 8 Site'
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
download_default_settings
init_settings
time site_install

#-------------------------- END: Execution --------------------------------
