<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function study_d8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.study_d8':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("This is the module Adam is using to learn Drupal 8. It includes several examples that may or may not make a whole lot of sense. Use at your own risk.") . '</p>';
      return $output;
  }
}
function study_d8_preprocess(&$variables, $hook, &$info) {
  if ($hook == 'node') {
    $contentTypeToShow = $variables['node']->bundle();
    if ($contentTypeToShow == 'article') {
      $templateFileName = 'node--article';
      $templateFilePath = drupal_get_path('module', 'study_d8') . '/templates/' . $templateFileName . '.html.twig';
      if (file_exists($templateFilePath)) {
        $info['theme path'] = drupal_get_path('module', 'study_d8');
        $info['path'] = drupal_get_path('module', 'study_d8') . '/templates';
        $info['template'] = $templateFileName;
      }
    }
  }
}



/*
 * Implements hook_theme()

function study_d8_theme() {
  $items = [
    'page' => [],
  ];
  return $items;
}
*
*/
/**
function study_d8_theme($existing, $type, $theme, $path) {
  return [
    'page__study_d8' => [
      
    ],
  ];
}

/**
 * Implements hook_theme().

function study_d8_theme() {
  $theme['page__study_d8'] = [
    'template' => 'page--study_d8',
    'base hook' => 'node',
  ];
  $theme['paragraph__card__study_d8'] = [
    'template' => 'paragraph--card--study_d8',
    'base hook' => 'paragraph',
  ];
  return $theme;
}
 */
/**
 * Process variables for paragraphs-items.tpl.php
function study_d8_preprocess_paragraphs_items(&$variables) {
  $variables['theme_hook_suggestions'][] = 'paragraphs_items__' . $variables['element']['#view_mode'];
}
 */
/**
 * Process variables for paragraphs-items.tpl.php

function YOURTHEMEORMODULE_preprocess_paragraphs_items(&$variables) {
  $variables['theme_hook_suggestions'][] = 'paragraphs_items__' . $variables['element']['#view_mode'];
}


function study_d8_theme_registry_alter ( &$theme_registry ) {
	$theme_registry['paragraphs_item__card'] = [
		'template' => 'paragraphs-item--card',
		'path' => drupal_get_path('module', 'study_d8') . '/templates',
		'type' => 'paragraphs-item'
	];
}
 */